# Generated by Django 4.2 on 2023-07-25 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSensingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zname', models.CharField(max_length=200)),
                ('zpath', models.CharField(max_length=200)),
                ('MSname', models.CharField(max_length=200)),
                ('MSpath', models.CharField(max_length=200)),
                ('PAname', models.CharField(max_length=200)),
                ('PApath', models.CharField(max_length=200)),
                ('CloudPercent', models.FloatField()),
                ('GeodeticInfo', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
