# Generated by Django 3.2.19 on 2023-08-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadedfile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesensingdata',
            name='ProductTime',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotesensingdata',
            name='browsejpgpath',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
