# Generated by Django 3.2.19 on 2023-08-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230830_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotesensingdata',
            name='ProductTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='remotesensingdata',
            name='browsejpgpath',
            field=models.ImageField(upload_to='quickviews/'),
        ),
    ]
