# Generated by Django 3.2.19 on 2023-08-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230830_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotesensingdata',
            name='browsejpgpath',
            field=models.FilePathField(path='E:\\gggg\\myproject\\media'),
        ),
    ]
